name: Dependabot Auto Merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    # These permissions are required by the action
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.MYTOKEN }}  # classic PAT
          target: minor                         # only merge minor updates
          approve-only: false                   # approve + merge
          merge-method: squash                  # optional: squash, merge, or rebase
